spring:
  application:
    name: job-to-kafka-service
  profiles:
    active: job_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: job-to-kafka-service,config-client
      uri: http://localhost:8888
#      username: spring_cloud_user
#      password: '1234'
#
#log:
#  app-name: job-to-kafka-service
#
#job-to-kafka-service:
#  enable-mock-tweets: true
